# 1. model
model : Trans_SVNet.mstcn.MultiStageModel
input_height : 224
input_width : 224
out_features : 3
mstcn_layers : 8
mstcn_f_maps : 32
mstcn_f_dim: 2048
mstcn_stages : 2
# 2. module
module : Trans_SVNet.temporal_extractor.TransSVNetTemporalExtractor
class_weights: [1.0, 1.0, 1.0]
# 3. dataset
data_root : /home/ubuntu/data/prediction/TransSVNetSpatial/220405-164302_TransSVNetSpatialExtractor_MastoidPerFrameRawImgDataset_Trans_SVNet_ResNet50_ResNet50TransSV/
metadata_file: "TransSVNet_Spatial_Features_metadata.pkl"
dataset : Trans_SVNet.trans_svnet_datasets.TransSVNetTempporalPerVideoDataset
datamodule: mastoid.mastoid_datamodule.MastoidDataModule
sequence_length : -1
num_workers : 8       # for dataloader
video_index_col_name : "video_index"
train_video_indexes : [1, 3, 4, 5, 6, 7]
val_video_indexes : [8, 9, 10]
test_video_indexes : [12, 13, 14]
pred_video_indexes : [1]
original_fps : 1
train_downsampled_fps : 1
val_downsampled_fps : 1
test_downsampled_fps : 1
# dataset transform
transform: mastoid.mastoid_transform.MastoidTrasform
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
apply_training_aug: False
# 4. training
gpus : 0 # all available -1
early_stopping_metric : val_acc
early_stopping_metric_mode: max
batch_size : 1
learning_rate : 0.00007
min_epochs : 12
max_epochs : 16
# resume_from_checkpoint : /home/ubuntu/phase_detection/DL/logs/220405-164302_TransSVNetSpatialExtractor_MastoidPerFrameRawImgDataset_Trans_SVNet_ResNet50_ResNet50TransSV/checkpoints/epoch=2-val_acc=0.71.ckpt
# prediction_output_path: /home/ubuntu/data/prediction/TransSVNetSpatial/220405-164302_TransSVNetSpatialExtractor_MastoidPerFrameRawImgDataset_Trans_SVNet_ResNet50_ResNet50TransSV
