# 1. model
model : WILDCAT.wildcat.ResNetWSL50
input_height : 225
input_width : 400
num_classes : 5
# 2. module
module : mastoid.mastoid_module_base.MastoidModuleBase
metrics_callback : mastoid.mastoid_metrics_callback_base.MastoidMetricsCallbackBase
predictions_callback : WILDCAT.wildcat_wsl.WildcatWSLPredClbk
class_weights: [1.0, 1.0, 1.0, 1.0, 1.0]
class_names: ["cut_on", "cut_off", "diamond_on", "diamond_off", "no_drill"]
# 3. dataset
data_root : /home/ubuntu/data/mastoid_400225_downsampled
metadata_file: "tool_annotations.csv"
path_col_name: "path"
video_index_col_name: "vid_idx"
dataset : tool_map.tool_map_dataset.ToolMapDataset
datamodule: mastoid.mastoid_datamodule.MastoidDataModule
sequence_length : 1
num_workers : 64      # for dataloader
train_video_indexes : [1, 2, 3, 4, 13]
val_video_indexes : [14]
test_video_indexes : [14]
pred_video_indexes : [1, 2, 3, 4, 13, 14]
original_fps : 1
train_downsampled_fps : 1
val_downsampled_fps : 1
test_downsampled_fps : 1
pred_downsampled_fps : 1
# dataset transform
transform: mastoid.mastoid_transform.MastoidTrasform
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
apply_training_aug: False
# 4. training
project: wildcat_tool_map
experiment_name: testing
gpus : 0 # all available -1
early_stopping_metric : val_loss
early_stopping_metric_mode: min
batch_size : 100
learning_rate : 0.000001
min_epochs : 10
max_epochs : 20
resume_from_checkpoint: /home/ubuntu/phase_detection/DL/logs/220624-090613_testing/checkpoints/epoch=19-val_loss=0.26.ckpt
prediction_output_path: /home/ubuntu/data/prediction/WILDCAT/220624-090613_testing