# 1. model
model : Trans_SVNet.res_net50.ResNet50TransSV
input_height : 225
input_width : 400
out_features : 3
# 2. module
module : mastoid.mastoid_module_base.MastoidModuleBase
metrics_callback : mastoid.mastoid_metrics_callback_base.MastoidMetricsCallbackBase
predictions_callback : Trans_SVNet.spatial_extractor.TransSVNetSpatExtClbk
class_weights: [1.0, 2.019093793836055, 0.6161134683394908]
class_names: ["expose", "antrum", "facial"]
# 3. dataset
data_root : /home/ubuntu/data/mastoid_400225_new
metadata_file: "mastoid_split_250px_30fps.pkl"
path_col_name: "image_path"
dataset : mastoid.mastoid_dataset.MastoidPerFrameRawImgDataset
datamodule: mastoid.mastoid_datamodule.MastoidDataModule
sequence_length : 1
num_workers : 64      # for dataloader
train_video_indexes : [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
val_video_indexes : [1, 2, 3]
test_video_indexes : [1, 2, 3]
pred_video_indexes : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
original_fps : 30
train_downsampled_fps : 1
val_downsampled_fps : 1
test_downsampled_fps : 1
pred_downsampled_fps : 1
# dataset transform
transform: mastoid.mastoid_transform.MastoidTrasform
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
apply_training_aug: False
# 4. training
project: transsvnet
experiment_name: transsvnet_spatial_val_123
gpus : 0 # all available -1
early_stopping_metric : val_loss
early_stopping_metric_mode: min
batch_size : 100
learning_rate : 0.0005
min_epochs : 3
max_epochs : 6
# resume_from_checkpoint: /home/ubuntu/phase_detection/DL/logs/220418-120028_MastoidModuleBase_MastoidPerFrameRawImgDataset_Trans_SVNet_res_net50_ResNet50TransSV/checkpoints/epoch=2-val_acc=0.83.ckpt
# prediction_output_path: /home/ubuntu/data/prediction/TransSVNetSpatial/220418-120028_MastoidModuleBase_MastoidPerFrameRawImgDataset_Trans_SVNet_res_net50_ResNet50TransSV