# 1. model
model : Trans_SVNet.transformer.Transformer
input_height : 225
input_width : 400
num_classes : 3
n_layers : 1
n_heads : 8
mstcn_f_maps : 32
mstcn_f_dim: 2048
transformer_seq_length: 10
# 2. module
module : mastoid.mastoid_module_base.MastoidModuleBase
metrics_callback : mastoid.mastoid_metrics_callback_base.MastoidMetricsCallbackBase
predictions_callback : mastoid.mastoid_callbacks.MastoidPerVideoDatasetPredClbk
class_weights: [1.0, 2.019093793836055, 0.6161134683394908]
class_names: ["expose", "antrum", "facial"]
# 3. dataset
data_root : /home/ubuntu/data/prediction/TransSVNetTemporal/220424-131713_transsvnet_temporal_val_161718
metadata_file: "TransSVNet_Temporal_Features_metadata.pkl"
dataset : Trans_SVNet.trans_svnet_datasets.TransSVNetTransformerPerVideoDataset  
datamodule: mastoid.mastoid_datamodule.MastoidDataModule
sequence_length : -1
num_workers : 32       # for dataloader
video_index_col_name : "video_index"
train_video_indexes : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
val_video_indexes : [16, 17, 18]
test_video_indexes : [16, 17, 18]
pred_video_indexes : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
original_fps : 1
train_downsampled_fps : 1
val_downsampled_fps : 1
test_downsampled_fps : 1
# dataset transform
transform: mastoid.mastoid_transform.MastoidTrasform
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
apply_training_aug: False
# 4. training
project: transsvnet
experiment_name: transsvnet_transformer_val_161718
gpus : 1 # all available -1
early_stopping_metric : val_loss
early_stopping_metric_mode: min
batch_size : 1
learning_rate : 0.0001
min_epochs : 50
max_epochs : 100
resume_from_checkpoint : /home/ubuntu/phase_detection/DL/logs/220424-132303_transsvnet_transformer_val_161718/checkpoints/epoch=43-val_loss=0.58.ckpt
prediction_output_path: /home/ubuntu/data/prediction/TransSVNetTransformer/220424-132303_transsvnet_transformer_val_161718