# 1. model
model : Trans_SVNet.transformer.Transformer
input_height : 225
input_width : 400
out_features : 3
n_layers : 1
n_heads : 8
mstcn_f_maps : 32
mstcn_f_dim: 2048
transformer_seq_length: 10
# 2. module
# module : Trans_SVNet.transformer_aggregator.TransSVNetTransformerAggregator
module : mastoid.mastoid_module_base.MastoidModuleBase
metrics_callback : mastoid.mastoid_metrics_callback_base.MastoidMetricsCallbackBase
predictions_callback : mastoid.mastoid_callbacks.MastoidPerVideoDatasetPredClbk
class_weights: [1.0, 2.019093793836055, 0.6161134683394908]
class_names: ["expose", "antrum", "facial"]
# 3. dataset
data_root : /home/ubuntu/data/prediction/TransSVNetTemporal/220418-154650_TransSVNetTemporalExtractor_TransSVNetTemporalPerVideoDatasetSimple_Trans_SVNet_mstcn_MultiStageModel
metadata_file: "TransSVNet_Temporal_Features_metadata.pkl"
dataset : Trans_SVNet.trans_svnet_datasets.TransSVNetTransformerPerVideoDataset  
datamodule: mastoid.mastoid_datamodule.MastoidDataModule
sequence_length : -1
num_workers : 8       # for dataloader
video_index_col_name : "video_index"
train_video_indexes : [1, 3, 4, 6, 7, 10, 11, 12, 14]
val_video_indexes : [5, 8]
test_video_indexes : [5, 8]
pred_video_indexes : [1, 3, 4, 5, 6, 7, 8, 10, 11, 12, 14]
original_fps : 1
train_downsampled_fps : 1
val_downsampled_fps : 1
test_downsampled_fps : 1
# dataset transform
transform: mastoid.mastoid_transform.MastoidTrasform
norm_mean: [0.485, 0.456, 0.406]
norm_std: [0.229, 0.224, 0.225]
apply_training_aug: False
# 4. training
gpus : 1 # all available -1
early_stopping_metric : val_acc
early_stopping_metric_mode: max
batch_size : 1
learning_rate : 0.0001
min_epochs : 50
max_epochs : 100
resume_from_checkpoint : /home/ubuntu/phase_detection/DL/logs/220418-162158_MastoidModuleBase_TransSVNetTransformerPerVideoDataset_Trans_SVNet_transformer_Transformer/checkpoints/epoch=29-val_acc=0.86.ckpt         
prediction_output_path: /home/ubuntu/data/prediction/TransSVNetTransformer/220418-162158_MastoidModuleBase_TransSVNetTransformerPerVideoDataset_Trans_SVNet_transformer_Transformer
