module : cnn.feature_extraction.FeatureExtraction
model : cnn.ResNet50Model
# Need to modify the model to be single head
data_root : /home/ubuntu/data/mastoid_dataset
# Need to change the data root path
dataset : cholec80_feature_extract.MastoidFeatureExtract
# Dataset 
out_features : 3
# Output Feature = 3
input_height : 224
input_width : 224
batch_size : 128
fps_sampling : 1
fps_sampling_test : 30
# Change test fps to 30 
learning_rate : 0.0005
dataset_mode : img_signlelabel
# ?????
early_stopping_metric : val_acc_phase
pretrained : True
save_top_k : 1
max_epochs : 15 # 30
min_epochs : 6 # 20
#num_tasks : 2
num_tasks : 1
num_sanity_val_steps : 4
test_extract : True
#accelerator: ddp_spawn
num_workers : 10
gpus : 1 # all available -1
#resume_from_checkpoint : logs/201103-000243_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model/checkpoints/201103-000243_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model-epoch=10-val_acc_phase=0.83.ckpt
sequence_length: 4
stride: 1
